import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./components/Footer";
import Nav from "./components/Nav";
import { QuoteRequestOverlay } from "./components/QuoteRequestOverlay";
import { EstimateProvider } from "./contexts/EstimateContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        suppressHydrationWarning
      >
        <EstimateProvider>
          <Nav/>
          <main className="min-h-screen bg-background text-foreground mx-5 overflow-clip">
            {children}
          </main>
          <Footer/>
          <QuoteRequestOverlay />
        </EstimateProvider>
      </body>
    </html>
  );
}